# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('picture', models.ImageField(default='event_pics/circus.png', upload_to='event_pics/')),
                ('facebook_link', models.URLField()),
                ('picture_link', models.URLField(default='http://via.placeholder.com/350x150')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grad_year', models.IntegerField()),
                ('description', models.TextField()),
                ('major', models.CharField(default='Undeclared', max_length=30)),
                ('position', models.CharField(default='Intern', max_length=30)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(default='event_pics/circus.png', upload_to='officer_pics/')),
                ('ordering', models.IntegerField(default=10)),
            ],
        ),
    ]
