# Generated by Django 2.0.1 on 2018-02-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('facebook', models.URLField()),
                ('photo', models.FileField(upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Semester'),
        ),
    ]
