# Generated by Django 2.0.1 on 2018-02-28 07:42

from django.db import migrations, models
import django.db.models.deletion
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=public.models.EventImage.image_folder)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public.Event')),
            ],
        ),
    ]
