# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('grad_year', models.IntegerField()),
                ('description', models.TextField()),
                ('major', models.CharField(default='Undeclared', max_length=30)),
                ('position', models.CharField(default='General Member', max_length=30)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(default='event_pics/circus.png', upload_to='officer_pics/')),
                ('ordering', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
