# Generated by Django 2.0.1 on 2018-01-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20180113_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='event',
            name='semester',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture_link',
            field=models.URLField(),
        ),
    ]
