# Generated by Django 2.0.1 on 2018-02-28 08:00

from django.db import migrations, models
import public.models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_event_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(upload_to=public.models.Event.image_folder),
        ),
    ]
