# Generated by Django 2.0.1 on 2018-01-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20180113_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_file',
            field=models.FileField(default=None, upload_to='events_imgs'),
            preserve_default=False,
        ),
    ]
