# Generated by Django 2.0.1 on 2018-01-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_event_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_file',
        ),
    ]
