# Generated by Django 2.0.1 on 2018-01-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_remove_event_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_file',
            field=models.FileField(default='', upload_to='events_imgs'),
            preserve_default=False,
        ),
    ]
