# Generated by Django 2.0.1 on 2018-02-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facebook',
        ),
    ]
