# Generated by Django 2.0.1 on 2018-01-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_remove_event_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_file',
            field=models.FileField(default=' ', upload_to='events_imgs'),
            preserve_default=False,
        ),
    ]
